mutation UpdateUser(
    $profileColor: String,
    $animeListOptions: MediaListOptionsInput,
    $mangaListOptions: MediaListOptionsInput,
) {
    UpdateUser(
        profileColor: $profileColor,
        animeListOptions: $animeListOptions
        mangaListOptions: $mangaListOptions
    ) {
        options {
            profileColor
        }
        mediaListOptions {
            animeList {
                sectionOrder
            }
            mangaList {
                sectionOrder
            }
        }
    }
}
