name: code-scanning

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '31 22 * * *'

jobs:
  detekt:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run Detekt
        continue-on-error: true
        run: ./gradlew detekt detektMerge --continue

      - name: Submit Detekt report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: build/reports/detekt/merge.sarif

  lint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run Lint
        continue-on-error: true
        run: ./gradlew app:lint --continue

      - name: Submit Lint report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: app/build/reports/lint-results-debug.sarif
